#!/bin/sh

#module load python/3.5.1
module load bcftools/1.9.0
module load samtools/1.9.0
module load htslib/1.9.0 
module load vcftools/0.1.16
module load beagle/4.1
module load germline/1.5.3
#module load R/3.2.5
module load pandoc/1.12.3

~/.local/bin/snakemake "$@"
