#!/usr/bin/env bash

PWD="$(cd `dirname $0`; pwd)"

export PATH="${PWD}/scripts:${PATH}"
echo "Path: ${PATH}"

RCFILE="$HOME/.tribesrc"

if [ -e "$RCFILE" ]; then
    echo "Loading rcfile: '$RCFILE'"
    source "$RCFILE"
fi

SNAKEMAKE="${SNAKEMAKE:-snakemake}"
echo "Running with: ${SNAKEMAKE}"

"${SNAKEMAKE}" "$@"
