---
title: "IBD_analysis_perDegree"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, fig.width=12, fig.height=8)
```

```{r echo=FALSE, warning=FALSE}
library(ggplot2)
library(dplyr)
library(tribes.tools)
```

```{r echo=FALSE, warning=TRUE}
#Snakemake interface
args = list()
if (exists('snakemake')) {
    args = list(estimatedRelFile = snakemake@input$estRel, 
                trueRelFile = snakemake@input$trueRel)
    
} else {
    warning("Not running with snakemake. Using test arguments!!!")
    args = list(estimatedRelFile = '~/tmp/tribes/TFEur/FF-EUR-15-30-2-mut_BiSnp_EurAF:0.01_LD_PH_GRM-allchr_IBD.csv', 
                trueRelFile = '~/tmp/tribes/TFEur/FF-EUR-15-30-2-mut_relations.txt')
}
print(args)
```

```{r}
estimatedRelations <- normalizeRelations(read.csv(args$estimatedRelFile, header = TRUE, stringsAsFactors = FALSE) %>% 
    mutate(EstDegree = as.relDegree(EstDegree)))
trueRelations <- readRelations(args$trueRelFile)
estimateRelationsWithTrue <- left_join(trueRelations, estimatedRelations, by=c('Id1', 'Id2')) %>%
    mutate(
        EstDegree = na.replace(EstDegree, as.relDegree('UR')), 
        IBD0.cM = na.replace(IBD0.cM, 1.0)
    )
head(estimateRelationsWithTrue)
```

```{r}
#group and count by Known degree:Predicted degree combination
estimatedVsTruth <- estimateRelationsWithTrue %>%
  group_by(Degree, EstDegree) %>%
  count()

head(estimatedVsTruth)
```


```{r}
#make plot comparing estimated to true degree - excluding unrelated as it distorts scale
print(
    ggplot(estimatedVsTruth, aes(Degree, EstDegree)) 
        + geom_point(aes(size = n)) 
        + geom_text(aes(label=n),hjust=0.5, vjust=-1, colour='red') 
        + theme_bw()
        + labs(title="Predicted vs True with UR",
                        y="Estimated degree of relationship",
                        x="Degree of reported relationship")
)
```


```{r}
#make plot comparing estimated to true degree - excluding unrelated as it distorts scale
print(
    ggplot(estimatedVsTruth %>% filter(Degree != "UR") , aes(Degree, EstDegree)) 
        + geom_point(aes(size = n)) 
        + geom_text(aes(label=n),hjust=0.5, vjust=-1, colour='red') 
        + theme_bw()
        + labs(title="Predicted vs True no UR",
                        y="Estimated degree of relationship",
                        x="Degree of reported relationship")
)
```
